import React, { Component } from 'react';
import { Provider } from 'react-redux';
import { ThemeProvider } from 'styled-components';
import styled from 'styled-components';

import Home from 'components/pages/Home';

import theme from './theme';

import store from './store';

const Wrapper = styled.section`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;

class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <ThemeProvider theme={theme}>
          <Wrapper>
            <Home />
          </Wrapper>
        </ThemeProvider>
      </Provider>
    );
  }
}

// [
//   {
//     alignment: 'Lawful Good',
//     ascensions: [],
//     attribute: 'Earth',
//     base_atk: 1261,
//     base_hp: 1854,
//     class: 'Shielder',
//     cost: '0',
//     gamepress_url: 'https://grandorder.gamepress.gg/servant/mash-kyrielight',
//     gender: 'Female',
//     grail_atk: 10575,
//     grail_hp: 15619,
//     growth_curve: 'Linear',
//     id: '1',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0011.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0012.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0013.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0014.jpg',

//     max_atk: 6791,
//     max_hp: 10302,
//     name: 'Mash Kyrielight',
//     rarity: 3,
//     seiyuu: 'Takahashi Rie',
//     skill_1: 'Transient Wall of Snowflakes',
//     skill_2: 'Exalted Impervious Wall of Snowflakes',
//     skill_3: 'Obscurant Wall of Chalk',
//     skill_ups: [
//       [2, 'proof_of_hero', 5],
//       [3, 'dragon_fang', 5],
//       [4, 'seed_of_yggdrassil', 5],
//       [5, 'octuplet_twin_crystals', 5],
//       [6, 'voids_dust', 5],
//       [7, 'eternal_gear', 5],
//       [8, 'phoenix_feather', 5],
//       [9, 'dragons_reverse_scale', 5],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'Lawful Good',
//     ascensions: [
//       [1, 'saber_piece', 5],
//       [2, 'dragon_fang', 18],
//       [2, 'saber_piece', 12],
//       [3, 'phoenix_feather', 4],
//       [3, 'proof_of_hero', 29],
//       [3, 'saber_monument', 5],
//       [4, 'phoenix_feather', 8],
//       [4, 'dragons_reverse_scale', 5],
//       [4, 'saber_monument', 12],
//     ],
//     attribute: 'Earth',
//     base_atk: 1734,
//     base_hp: 2222,
//     class: 'Saber',
//     cost: '16',
//     gamepress_url: 'https://grandorder.gamepress.gg/servant/altria-pendragon',
//     gender: 'Female',
//     grail_atk: 12283,
//     grail_hp: 16597,
//     growth_curve: 'Linear',
//     id: '2',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0021.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0022.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0023.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0024.jpg',

//     max_atk: 11221,
//     max_hp: 15150,
//     name: 'Altria Pendragon',
//     rarity: 5,
//     seiyuu: 'Ayako Kawasumi',
//     skill_1: 'Charisma B',
//     skill_2: 'Mana Burst A',
//     skill_3: 'Intuition A',
//     skill_ups: [
//       [2, 'gem_of_saber', 5],
//       [3, 'gem_of_saber', 12],
//       [4, 'magic_gem_of_saber', 5],
//       [5, 'magic_gem_of_saber', 12],
//       [5, 'proof_of_hero', 15],
//       [6, 'secret_gem_of_saber', 5],
//       [6, 'proof_of_hero', 29],
//       [7, 'secret_gem_of_saber', 12],
//       [7, 'dragon_fang', 12],
//       [8, 'dragon_fang', 24],
//       [8, 'claw_of_chaos', 4],
//       [9, 'claw_of_chaos', 11],
//       [9, 'dragons_reverse_scale', 10],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'Lawful Evil',
//     ascensions: [
//       [1, 'saber_piece', 4],
//       [2, 'saber_piece', 10],
//       [2, 'dragon_fang', 15],
//       [3, 'saber_monument', 4],
//       [3, 'claw_of_chaos', 5],
//       [3, 'dragons_reverse_scale', 2],
//       [4, 'saber_monument', 10],
//       [4, 'dragons_reverse_scale', 4],
//       [4, 'heart_of_the_foreign_god', 4],
//     ],
//     attribute: 'Mankind',
//     base_atk: 1708,
//     base_hp: 1854,
//     class: 'Saber',
//     cost: '12',
//     gamepress_url:
//       'https://grandorder.gamepress.gg/servant/altria-pendragon-alter',
//     gender: 'Female',
//     grail_atk: 12408,
//     grail_hp: 14051,
//     growth_curve: 'S',
//     id: '3',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0031.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0032.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0033.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0034.jpg',

//     max_atk: 10248,
//     max_hp: 11589,
//     name: 'Altria Pendragon (Alter)',
//     rarity: 4,
//     seiyuu: 'Ayako Kawasumi',
//     skill_1: 'Mana Burst A',
//     skill_2: 'Intuition B',
//     skill_3: 'Charisma E',
//     skill_ups: [
//       [2, 'gem_of_saber', 4],
//       [3, 'gem_of_saber', 10],
//       [4, 'magic_gem_of_saber', 4],
//       [5, 'magic_gem_of_saber', 10],
//       [5, 'claw_of_chaos', 3],
//       [6, 'secret_gem_of_saber', 4],
//       [6, 'claw_of_chaos', 5],
//       [7, 'secret_gem_of_saber', 10],
//       [7, 'dragon_fang', 10],
//       [8, 'dragon_fang', 20],
//       [8, 'voids_dust', 10],
//       [9, 'voids_dust', 30],
//       [9, 'heart_of_the_foreign_god', 8],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'Lawful Good',
//     ascensions: [
//       [1, 'saber_piece', 4],
//       [2, 'saber_piece', 10],
//       [2, 'proof_of_hero', 18],
//       [3, 'saber_monument', 4],
//       [3, 'dragon_fang', 20],
//       [3, 'seed_of_yggdrassil', 5],
//       [4, 'saber_monument', 10],
//       [4, 'seed_of_yggdrassil', 10],
//       [4, 'dragons_reverse_scale', 4],
//     ],
//     attribute: 'Earth',
//     base_atk: 1287,
//     base_hp: 1699,
//     class: 'Saber',
//     cost: '12',
//     gamepress_url:
//       'https://grandorder.gamepress.gg/servant/altria-pendragon-lily',
//     gender: 'Female',
//     grail_atk: 9355,
//     grail_hp: 12880,
//     growth_curve: 'S',
//     id: '4',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0041.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0042.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0043.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0044.jpg',

//     max_atk: 7726,
//     max_hp: 10623,
//     name: 'Altria Pendragon (Lily)',
//     rarity: 4,
//     seiyuu: 'Ayako Kawasumi',
//     skill_1: 'Intuition B',
//     skill_2: 'Mana Burst A',
//     skill_3: 'Journey of the Flowers EX',
//     skill_ups: [
//       [2, 'gem_of_saber', 4],
//       [3, 'gem_of_saber', 10],
//       [4, 'magic_gem_of_saber', 4],
//       [5, 'magic_gem_of_saber', 10],
//       [5, 'dragon_fang', 10],
//       [6, 'secret_gem_of_saber', 4],
//       [6, 'dragon_fang', 20],
//       [7, 'secret_gem_of_saber', 10],
//       [7, 'proof_of_hero', 12],
//       [8, 'proof_of_hero', 24],
//       [8, 'claw_of_chaos', 3],
//       [9, 'claw_of_chaos', 9],
//       [9, 'dragons_reverse_scale', 8],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'Chaotic Good',
//     ascensions: [
//       [1, 'saber_piece', 4],
//       [2, 'saber_piece', 10],
//       [2, 'octuplet_twin_crystals', 6],
//       [3, 'saber_monument', 4],
//       [3, 'phoenix_feather', 7],
//       [3, 'ghost_lantern', 4],
//       [4, 'saber_monument', 10],
//       [4, 'ghost_lantern', 8],
//       [4, 'eternal_gear', 10],
//     ],
//     attribute: 'Mankind',
//     base_atk: 1574,
//     base_hp: 1880,
//     class: 'Saber',
//     cost: '12',
//     gamepress_url: 'https://grandorder.gamepress.gg/servant/nero-claudius',
//     gender: 'Female',
//     grail_atk: 11441,
//     grail_hp: 14250,
//     growth_curve: 'Reverse S',
//     id: '5',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0051.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0052.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0053.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0054.jpg',

//     max_atk: 9449,
//     max_hp: 11753,
//     name: 'Nero Claudius',
//     rarity: 4,
//     seiyuu: 'Sakura Tange',
//     skill_1: 'Migraine B',
//     skill_2: 'Imperial Privilege EX',
//     skill_3: 'Thrice-Setting Sun A',
//     skill_ups: [
//       [2, 'gem_of_saber', 4],
//       [3, 'gem_of_saber', 10],
//       [4, 'magic_gem_of_saber', 4],
//       [5, 'magic_gem_of_saber', 10],
//       [5, 'phoenix_feather', 4],
//       [6, 'secret_gem_of_saber', 4],
//       [6, 'phoenix_feather', 7],
//       [7, 'secret_gem_of_saber', 10],
//       [7, 'octuplet_twin_crystals', 4],
//       [8, 'octuplet_twin_crystals', 8],
//       [8, 'dragon_fang', 12],
//       [9, 'dragon_fang', 36],
//       [9, 'eternal_gear', 20],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'Chaotic Good',
//     ascensions: [
//       [1, 'saber_piece', 4],
//       [2, 'saber_piece', 10],
//       [2, 'dragon_fang', 15],
//       [3, 'saber_monument', 4],
//       [3, 'seed_of_yggdrassil', 10],
//       [3, 'proof_of_hero', 12],
//       [4, 'saber_monument', 10],
//       [4, 'proof_of_hero', 24],
//       [4, 'dragons_reverse_scale', 5],
//     ],
//     attribute: 'Earth',
//     base_atk: 1363,
//     base_hp: 2266,
//     class: 'Saber',
//     cost: '12',
//     gamepress_url: 'https://grandorder.gamepress.gg/servant/siegfried',
//     gender: 'Male',
//     grail_atk: 9905,
//     grail_hp: 17175,
//     growth_curve: 'S',
//     id: '6',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0061.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0062.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0063.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0064.jpg',

//     max_atk: 8181,
//     max_hp: 14165,
//     name: 'Siegfried',
//     rarity: 4,
//     seiyuu: 'Junichi Suwabe',
//     skill_1: 'Golden Rule C-',
//     skill_2: 'Disengage A',
//     skill_3: 'Dragon-Slayer A',
//     skill_ups: [
//       [2, 'gem_of_saber', 4],
//       [3, 'gem_of_saber', 10],
//       [4, 'magic_gem_of_saber', 4],
//       [5, 'magic_gem_of_saber', 10],
//       [5, 'seed_of_yggdrassil', 5],
//       [6, 'secret_gem_of_saber', 4],
//       [6, 'seed_of_yggdrassil', 10],
//       [7, 'secret_gem_of_saber', 10],
//       [7, 'dragon_fang', 10],
//       [8, 'dragon_fang', 20],
//       [8, 'heart_of_the_foreign_god', 2],
//       [9, 'heart_of_the_foreign_god', 6],
//       [9, 'dragons_reverse_scale', 8],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'True Neutral',
//     ascensions: [
//       [1, 'saber_piece', 4],
//       [2, 'saber_piece', 8],
//       [2, 'proof_of_hero', 15],
//       [3, 'saber_monument', 4],
//       [3, 'eternal_gear', 7],
//       [3, 'forbidden_page', 4],
//       [4, 'saber_monument', 8],
//       [4, 'forbidden_page', 7],
//       [4, 'claw_of_chaos', 5],
//     ],
//     attribute: 'Mankind',
//     base_atk: 1392,
//     base_hp: 1727,
//     class: 'Saber',
//     cost: '7',
//     gamepress_url:
//       'https://grandorder.gamepress.gg/servant/gaius-julius-caesar',
//     gender: 'Male',
//     grail_atk: 10146,
//     grail_hp: 13009,
//     growth_curve: 'S',
//     id: '7',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0071.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0072.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0073.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0074.jpg',

//     max_atk: 7497,
//     max_hp: 9595,
//     name: 'Gaius Julius Caesar',
//     rarity: 3,
//     seiyuu: 'Ryoutarou Okiayu',
//     skill_1: 'Tactics B',
//     skill_2: 'Charisma C',
//     skill_3: 'Incitement EX',
//     skill_ups: [
//       [2, 'gem_of_saber', 4],
//       [3, 'gem_of_saber', 8],
//       [4, 'magic_gem_of_saber', 4],
//       [5, 'magic_gem_of_saber', 8],
//       [5, 'eternal_gear', 4],
//       [6, 'secret_gem_of_saber', 4],
//       [6, 'eternal_gear', 7],
//       [7, 'secret_gem_of_saber', 8],
//       [7, 'proof_of_hero', 10],
//       [8, 'proof_of_hero', 20],
//       [8, 'meteor_horseshoe', 4],
//       [9, 'meteor_horseshoe', 12],
//       [9, 'claw_of_chaos', 10],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'Chaotic Good',
//     ascensions: [
//       [1, 'saber_piece', 5],
//       [2, 'saber_piece', 12],
//       [2, 'voids_dust', 15],
//       [3, 'saber_monument', 5],
//       [3, 'claw_of_chaos', 6],
//       [3, 'meteor_horseshoe', 5],
//       [4, 'saber_monument', 12],
//       [4, 'meteor_horseshoe', 10],
//       [4, 'heart_of_the_foreign_god', 5],
//     ],
//     attribute: 'Mankind',
//     base_atk: 1907,
//     base_hp: 2039,
//     class: 'Saber',
//     cost: '16',
//     gamepress_url: 'https://grandorder.gamepress.gg/servant/altera',
//     gender: 'Female',
//     grail_atk: 13511,
//     grail_hp: 15236,
//     growth_curve: 'Linear',
//     id: '8',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0081.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0082.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0083.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0084.jpg',

//     max_atk: 12343,
//     max_hp: 13907,
//     name: 'Altera',
//     rarity: 5,
//     seiyuu: 'Mamiko Noto',
//     skill_1: 'Tactics B',
//     skill_2: 'Natural Body D',
//     skill_3: 'Natural Body EX',
//     skill_ups: [
//       [2, 'gem_of_saber', 5],
//       [3, 'gem_of_saber', 12],
//       [4, 'magic_gem_of_saber', 5],
//       [5, 'magic_gem_of_saber', 12],
//       [5, 'claw_of_chaos', 3],
//       [6, 'secret_gem_of_saber', 5],
//       [6, 'claw_of_chaos', 6],
//       [7, 'secret_gem_of_saber', 12],
//       [7, 'voids_dust', 10],
//       [8, 'voids_dust', 20],
//       [8, 'evil_bone', 18],
//       [9, 'evil_bone', 54],
//       [9, 'heart_of_the_foreign_god', 10],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'Lawful Good',
//     ascensions: [
//       [1, 'saber_piece', 4],
//       [2, 'saber_piece', 8],
//       [2, 'proof_of_hero', 15],
//       [3, 'saber_monument', 4],
//       [3, 'voids_dust', 13],
//       [3, 'evil_bone', 10],
//       [4, 'saber_monument', 8],
//       [4, 'evil_bone', 20],
//       [4, 'heart_of_the_foreign_god', 4],
//     ],
//     attribute: 'Mankind',
//     base_atk: 1228,
//     base_hp: 1889,
//     class: 'Saber',
//     cost: '7',
//     gamepress_url: 'https://grandorder.gamepress.gg/servant/gilles-de-rais',
//     gender: 'Male',
//     grail_atk: 8952,
//     grail_hp: 14234,
//     growth_curve: 'S',
//     id: '9',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0091.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0092.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0093.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0094.jpg',

//     max_atk: 6615,
//     max_hp: 10498,
//     name: 'Gilles de Rais',
//     rarity: 3,
//     seiyuu: 'Satoshi Tsuroka',
//     skill_1: 'Tactics C',
//     skill_2: 'Golden Rule B',
//     skill_3: "Prelati's Encouragement B",
//     skill_ups: [
//       [2, 'gem_of_saber', 4],
//       [3, 'gem_of_saber', 8],
//       [4, 'magic_gem_of_saber', 4],
//       [5, 'magic_gem_of_saber', 8],
//       [5, 'voids_dust', 7],
//       [6, 'secret_gem_of_saber', 4],
//       [6, 'voids_dust', 13],
//       [7, 'secret_gem_of_saber', 8],
//       [7, 'proof_of_hero', 10],
//       [8, 'proof_of_hero', 20],
//       [8, 'ghost_lantern', 4],
//       [9, 'ghost_lantern', 12],
//       [9, 'heart_of_the_foreign_god', 7],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
//   {
//     alignment: 'True Neutral',
//     ascensions: [
//       [1, 'saber_piece', 4],
//       [2, 'saber_piece', 10],
//       [2, 'proof_of_hero', 18],
//       [3, 'saber_monument', 4],
//       [3, 'seed_of_yggdrassil', 10],
//       [3, 'phoenix_feather', 4],
//       [4, 'saber_monument', 10],
//       [4, 'phoenix_feather', 7],
//       [4, 'serpent_jewel', 8],
//     ],
//     attribute: 'Mankind',
//     base_atk: 1460,
//     base_hp: 2121,
//     class: 'Saber',
//     cost: '12',
//     gamepress_url: 'https://grandorder.gamepress.gg/servant/chevalier-deon',
//     gender: 'OTHER',
//     grail_atk: 10613,
//     grail_hp: 16073,
//     growth_curve: 'Reverse S',
//     id: '10',
//     img1: 'https://fate-go.cirnopedia.org/icons/servant_card/0101.jpg',
//     img2: 'https://fate-go.cirnopedia.org/icons/servant_card/0102.jpg',
//     img3: 'https://fate-go.cirnopedia.org/icons/servant_card/0103.jpg',
//     img4: 'https://fate-go.cirnopedia.org/icons/servant_card/0104.jpg',

//     max_atk: 8765,
//     max_hp: 13256,
//     name: "Chevalier d'Eon",
//     rarity: 4,
//     seiyuu: 'Chiwa Saito',
//     skill_1: "Mind's Eye (True) C",
//     skill_2: 'Self-Suggestion A',
//     skill_3: 'Aspect of Beauty C',
//     skill_ups: [
//       [2, 'gem_of_saber', 4],
//       [3, 'gem_of_saber', 10],
//       [4, 'magic_gem_of_saber', 4],
//       [5, 'magic_gem_of_saber', 10],
//       [5, 'seed_of_yggdrassil', 5],
//       [6, 'secret_gem_of_saber', 4],
//       [6, 'seed_of_yggdrassil', 10],
//       [7, 'secret_gem_of_saber', 10],
//       [7, 'proof_of_hero', 12],
//       [8, 'proof_of_hero', 24],
//       [8, 'forbidden_page', 5],
//       [9, 'forbidden_page', 15],
//       [9, 'serpent_jewel', 16],
//       [10, 'crystallized_lore', 1],
//     ],
//   },
// ];

// [
//   {
//     id: '1',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0014.png',
//   },
//   {
//     id: '2',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0023.png',
//   },
//   {
//     id: '3',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0033.png',
//   },
//   {
//     id: '4',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0043.png',
//   },
//   {
//     id: '5',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0053.png',
//   },
//   {
//     id: '6',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0063.png',
//   },
//   {
//     id: '7',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0073.png',
//   },
//   {
//     id: '8',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0083.png',
//   },
//   {
//     id: '9',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0093.png',
//   },
//   {
//     id: '10',
//     icon: 'https://fate-go.cirnopedia.org/icons/servant/servant_0103.png',
//   },
// ];
export default App;
